;; -*- mode: emacs-lisp; coding: emacs-mule; -*-
;; --------------------------------------------------------------------------
;; Desktop File for Emacs
;; --------------------------------------------------------------------------
;; Created Tue Aug 18 17:23:40 2015
;; Desktop file format version 206
;; Emacs version 24.4.51.2
(setq revive:frame-configuration-to-restore
  '(progn 
     (revive:restore-frame '((tool-bar-position . top) (explicit-name) (icon-name) (bottom-divider-width . 0) (right-divider-width . 0) (top . 27) (left . 4) (unsplittable) (modeline . t) (width . 80) (height . 35) (fringe) (mouse-color . "black") (environment) (visibility . t) (cursor-color . "Red") (background-mode . light) (horizontal-scroll-bars . t) (fullscreen) (alpha) (scroll-bar-width . 15) (cursor-type . box) (auto-lower) (auto-raise) (icon-type) (title) (buffer-predicate) (tool-bar-lines . 1) (menu-bar-lines . 1) (right-fringe . 11) (left-fringe . 3) (line-spacing) (background-color . "White") (foreground-color . "Black") (vertical-scroll-bars . right) (internal-border-width . 0) (border-width . 0) (font . "-*-Monaco-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1") (fontsize . 0)) '(80 35 ((0 0 84 17) (0 17 84 34)) ((nil "*Warning*" 1 1 (nil)) (nil "*scratch*" 1 1 (nil)))))))

;; Global section:
(setq desktop-saved-frameset [frameset 1 (21971 52364 22294 0) (desktop . "206") "matt@velocity.local" nil nil ((((font-backend mac-ct ns) (fontsize . 0) (font . "-*-Monaco-normal-normal-normal-*-12-*-*-*-m-0-iso10646-1") (border-width . 0) (internal-border-width . 0) (vertical-scroll-bars . right) (foreground-color . "Black") (background-color . "White") (line-spacing) (left-fringe . 3) (right-fringe . 11) (menu-bar-lines . 1) (tool-bar-lines . 1) (title) (icon-type) (auto-raise) (auto-lower) (cursor-type . box) (scroll-bar-width . 15) (alpha) (fullscreen) (horizontal-scroll-bars . t) (display-type . color) (background-mode . light) (cursor-color . "Red") (visibility . t) (environment) (mouse-color . "black") (fringe) (frameset--id . "0F4B-1159-AA51-2979") (frameset--mini t . t) (height . 35) (width . 80) (modeline . t) (minibuffer . t) (unsplittable) (left . 4) (top . 27) (right-divider-width . 0) (bottom-divider-width . 0) (icon-name) (display . "velocity.local") (explicit-name) (tool-bar-position . top)) ((min-height . 8) (min-width . 10) (min-height-ignore . 4) (min-width-ignore . 7) (min-height-safe . 2) (min-width-safe . 2) (min-pixel-height . 128) (min-pixel-width . 70) (min-pixel-height-ignore . 64) (min-pixel-width-ignore . 43) (min-pixel-height-safe . 32) (min-pixel-width-safe . 14)) vc (pixel-width . 589) (pixel-height . 544) (total-width . 84) (total-height . 34) (normal-height . 1.0) (normal-width . 1.0) (combination-limit) (leaf (pixel-width . 589) (pixel-height . 272) (total-width . 84) (total-height . 17) (normal-height . 0.5) (normal-width . 1.0) (buffer "*Warning*" (selected) (hscroll . 0) (fringes 3 11 nil) (margins nil) (scroll-bars 15 3 t nil) (vscroll . 0) (dedicated) (point . 1) (start . 1))) (leaf (last . t) (pixel-width . 589) (pixel-height . 272) (total-width . 84) (total-height . 17) (normal-height . 0.5) (normal-width . 1.0) (buffer "*scratch*" (selected . t) (hscroll . 0) (fringes 3 11 nil) (margins nil) (scroll-bars 15 3 t nil) (vscroll . 0) (dedicated) (point . 1) (start . 1)))))])
(setq desktop-missing-file-warning nil)
(setq tags-file-name nil)
(setq tags-table-list nil)
(setq search-ring nil)
(setq regexp-search-ring nil)
(setq register-alist nil)
(setq file-name-history '("~/.eamcs" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/php-mode-20150729.213/php-mode-autoloads.el" "~/.homesick/repos/adventure-castle/home/.emacs" "~/.emacs" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/magit-20150817.2214/magit-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/git-commit-20150817.2213/git-commit-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/with-editor-20150816.1106/with-editor-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/magit-popup-20150816.1106/magit-popup-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/dash-20150804.1354/dash-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/json-mode-20150413.1948/json-mode-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/json-reformat-20150406.1705/json-reformat-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/json-snatcher-20150511.2047/json-snatcher-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/helm-ls-git-20150815.734/helm-ls-git-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/helm-20150815.2342/helm-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/helm-core-20150816.108/helm-core-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/async-20150817.2321/async-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/sublimity-20150601.1137/sublimity-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/go-mode-20150817.2318/go-mode-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/go-errcheck-20150801.1428/go-errcheck-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/egg-20150208.1815/egg-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/column-marker-20121128.843/column-marker-autoloads.el" "~/Library/Preferences/Aquamacs Emacs/Packages/elpa/arduino-mode-20150503.758/arduino-mode-autoloads.el" "~/.ido.last" "~/Desktop/api_wrapper.rb" "~/Applications/GoToMeeting (2331).app/Contents/Info.plist"))

;; Buffer section -- buffers listed in same order as in buffer list:
